sudo: required
services:
  - docker

before_install:
  - docker build -t dsh2046/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dsh2046/react-test npm test

after_success:
  - docker build -t dsh2046/multi-client ./client
  - docker build -t dsh2046/multi-nginx ./nginx
  - docker build -t dsh2046/multi-server ./server
  - docker build -t dsh2046/multi-worker ./worker
  # Login to docker hub cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images push them to Docker hub
  - docker push dsh2046/multi-client
  - docker push dsh2046/multi-nginx
  - docker push dsh2046/multi-server
  - docker push dsh2046/multi-worker